"""db_config

Revision ID: de871710e5d0
Revises:
Create Date: 2024-01-08 21:13:12.624807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "de871710e5d0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dicomlog",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(), "mysql")
            .with_variant(sa.BIGINT(), "postgresql")
            .with_variant(sa.INTEGER(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("series_name", sa.String(length=256), nullable=False),
        sa.Column("input_path", sa.String(length=1024), nullable=False),
        sa.Column("output_path", sa.String(length=1024), nullable=True),
        sa.Column(
            "status",
            sa.Enum("INIT", "STARTED", "PREDICTED", "SENT", name="status"),
            server_default="INIT",
            nullable=False,
        ),
        sa.Column("model", sa.Enum("TSGyne", "TSPrime", name="model"), nullable=False),
        sa.Column(
            "created_on",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_name"),
    )
    op.create_index(op.f("ix_dicomlog_status"), "dicomlog", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dicomlog_status"), table_name="dicomlog")
    op.drop_table("dicomlog")
    # ### end Alembic commands ###
