# Generated by Django 4.2.17 on 2025-01-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_fileuploadmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadmetadata',
            name='file_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
