# Generated by Django 4.2.17 on 2025-01-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_fileuploadmetadata_file_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadmetadata',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'In Queue'), ('done', 'Segmentation Done'), ('file_sent', 'File Sent')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='fileuploadmetadata',
            name='result_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
